# Generated by Django 5.0.6 on 2024-06-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
